FROM node:alpine as build-stage

ADD . /app
#切换目录，指定编译源码位置
WORKDIR /app

COPY package.json ./

RUN npm install -g pnpm --registry=https://registry.npmmirror.com
RUN pnpm install --registry=https://registry.npmmirror.com
RUN pnpm build

FROM nginx:alpine
#将打包后的文件夹挪到nginx

COPY  --from=build-stage /app/dist /usr/share/nginx/html
COPY --from=build-stage /app/nginx.conf /etc/nginx/nginx.conf

# docker build -t docker-vite --build-arg envType=dev .
ARG envType=default_value
ARG envType
RUN echo "${envType}"


EXPOSE 80
